### ISSUE TITLE
Cancel, confirm, delete buttons in create flow

### ISSUE THREAD

**Issue by EatOreo** [00kristian/SYST#117]
Cancel doesn't cancel everything in some cases

**Comment by Julu8** [comment]
Edit Quiz -> when a new question is added and then cancelled then the new question is still there -> talk in group if this is okay or if it needs to be changed

**Comment by Julu8** [comment]
Could make a pop-up when cancelling out of Edit Quiz -> that remidns the user that if the user has created any questions, then they need to delete them if they don't wish them to be there before exiting

**Comment by 00kristian** [comment]
slet cancel knapperne
